#!/usr/bin/env python
# -*- coding: utf-8 -*-

'''
Problem 45

Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

    Triangle        Tn=n(n+1)/2     1, 3, 6,  10, 15, ...
    Pentagonal      Pn=n(3n−1)/2    1, 5, 12, 22, 35, ...
    Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''


def triangle(n):
    return n * (n + 1) / 2


def pentagonal(n):
    return n * (3 * n - 1) / 2


def hexagonal(n):
    return n * (2 * n - 1)


t = [triangle(n) for n in range(60000)]
p = [pentagonal(n) for n in range(60000)]
h = [hexagonal(n) for n in range(60000)]

print list(set(t).intersection(p).intersection(h))[-1]
