#!/usr/bin/env python
# -*- coding: utf-8 -*-

'''
Problem 44

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten
pentagonal numbers are:

    1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum
and difference are pentagonal and D = |Pk − Pj| is minimised; what is
the value of D?
'''

import sys


def pentagonal(n):
    return n * (3 * n - 1) / 2


p = set()
n = 1
k = 2

while True:
    while pentagonal(n) < pentagonal(k) + pentagonal(k - 1):
        p.add(pentagonal(n))
        n += 1
    for j in range(1, k):
        if pentagonal(k) - pentagonal(j) in p and pentagonal(k) + pentagonal(
                j) in p:
            print pentagonal(k) - pentagonal(j)
            sys.exit()
    k += 1
